substitutions:
    _NAME: funda-image-downloader # default value
    _VERSION: latest # default value
steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_NAME}:${SHORT_SHA}${_VERSION}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/${_NAME}:${SHORT_SHA}${_VERSION}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - ${_NAME}
      - --image
      - eu.gcr.io/$PROJECT_ID/${_NAME}:${SHORT_SHA}${_VERSION}
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
